name: Build on release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install uglify-js
    - run: npx uglify-js browser-control-card.js --compress --output browser-control-card.js
    - name: Upload release asset
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{github.event.release.tag_name}} browser-control-card.js
